[package]
authors = ['Joystream']
edition = '2018'
name = 'joystream-node-runtime'
version = '6.1.0'

[features]
default = ['std']
no_std = []
std = [
    'authority-discovery-primitives/std',
    'authority-discovery/std',
    'authorship/std',
    'finality-tracker/std',
    'im-online/std',
    'session/std',
    'offences/std',
    'sr-staking-primitives/std',
    'staking/std',
    'codec/std',
    'substrate-client/std',
    'rstd/std',
    'runtime-io/std',
    'srml-support/std',
    'balances/std',
    'babe/std',
    'babe-primitives/std',
    'executive/std',
    'indices/std',
    'grandpa/std',
    'primitives/std',
    'runtime-primitives/std',
    'system/std',
    'timestamp/std',
    'sudo/std',
    'version/std',
    'serde',
    'safe-mix/std',
    'offchain-primitives/std',
    'substrate-session/std',
    'forum/std',
    'versioned-store/std',
    'node-primitives/std'
]

[dependencies.babe]
default-features = false
git = 'https://github.com/paritytech/substrate.git'
package = 'srml-babe'
rev = 'a2a0eb5398d6223e531455b4c155ef053a4a3a2b'

[dependencies.babe-primitives]
default-features = false
git = 'https://github.com/paritytech/substrate.git'
package = 'substrate-consensus-babe-primitives'
rev = 'a2a0eb5398d6223e531455b4c155ef053a4a3a2b'

[dependencies.balances]
default_features = false
git = 'https://github.com/paritytech/substrate.git'
package = 'srml-balances'
rev = 'a2a0eb5398d6223e531455b4c155ef053a4a3a2b'

[dependencies.substrate-client]
default_features = false
git = 'https://github.com/paritytech/substrate.git'
package = 'substrate-client'
rev = 'a2a0eb5398d6223e531455b4c155ef053a4a3a2b'

[dependencies.codec]
default-features = false
features = ['derive']
package = 'parity-scale-codec'
version = '1.0.0'

[dependencies.executive]
default_features = false
git = 'https://github.com/paritytech/substrate.git'
package = 'srml-executive'
rev = 'a2a0eb5398d6223e531455b4c155ef053a4a3a2b'

[dependencies.grandpa]
default-features = false
git = 'https://github.com/paritytech/substrate.git'
package = 'srml-grandpa'
rev = 'a2a0eb5398d6223e531455b4c155ef053a4a3a2b'

[dependencies.indices]
default_features = false
git = 'https://github.com/paritytech/substrate.git'
package = 'srml-indices'
rev = 'a2a0eb5398d6223e531455b4c155ef053a4a3a2b'

[dependencies.offchain-primitives]
default-features = false
git = 'https://github.com/paritytech/substrate.git'
package = 'substrate-offchain-primitives'
rev = 'a2a0eb5398d6223e531455b4c155ef053a4a3a2b'

[dependencies.primitives]
default_features = false
git = 'https://github.com/paritytech/substrate.git'
package = 'substrate-primitives'
rev = 'a2a0eb5398d6223e531455b4c155ef053a4a3a2b'

[dependencies.rstd]
default_features = false
git = 'https://github.com/paritytech/substrate.git'
package = 'sr-std'
rev = 'a2a0eb5398d6223e531455b4c155ef053a4a3a2b'

[dependencies.runtime-io]
default_features = false
git = 'https://github.com/paritytech/substrate.git'
package = 'sr-io'
rev = 'a2a0eb5398d6223e531455b4c155ef053a4a3a2b'

[dependencies.safe-mix]
default-features = false
version = '1.0'

[dependencies.serde]
features = ['derive']
optional = true
version = '1.0'

[dependencies.runtime-primitives]
default_features = false
git = 'https://github.com/paritytech/substrate.git'
package = 'sr-primitives'
rev = 'a2a0eb5398d6223e531455b4c155ef053a4a3a2b'

[dependencies.substrate-session]
default-features = false
git = 'https://github.com/paritytech/substrate.git'
rev = 'a2a0eb5398d6223e531455b4c155ef053a4a3a2b'

[dependencies.sudo]
default_features = false
git = 'https://github.com/paritytech/substrate.git'
package = 'srml-sudo'
rev = 'a2a0eb5398d6223e531455b4c155ef053a4a3a2b'

[dependencies.srml-support]
default_features = false
git = 'https://github.com/paritytech/substrate.git'
package = 'srml-support'
rev = 'a2a0eb5398d6223e531455b4c155ef053a4a3a2b'

[dependencies.system]
default_features = false
git = 'https://github.com/paritytech/substrate.git'
package = 'srml-system'
rev = 'a2a0eb5398d6223e531455b4c155ef053a4a3a2b'

[dependencies.timestamp]
default_features = false
git = 'https://github.com/paritytech/substrate.git'
package = 'srml-timestamp'
rev = 'a2a0eb5398d6223e531455b4c155ef053a4a3a2b'

[dependencies.version]
default_features = false
git = 'https://github.com/paritytech/substrate.git'
package = 'sr-version'
rev = 'a2a0eb5398d6223e531455b4c155ef053a4a3a2b'

[dependencies.authority-discovery-primitives]
default_features = false
git = 'https://github.com/paritytech/substrate.git'
package = 'substrate-authority-discovery-primitives'
rev = 'a2a0eb5398d6223e531455b4c155ef053a4a3a2b'

[dependencies.authority-discovery]
default_features = false
git = 'https://github.com/paritytech/substrate.git'
package = 'srml-authority-discovery'
rev = 'a2a0eb5398d6223e531455b4c155ef053a4a3a2b'

[dependencies.authorship]
default_features = false
git = 'https://github.com/paritytech/substrate.git'
package = 'srml-authorship'
rev = 'a2a0eb5398d6223e531455b4c155ef053a4a3a2b'

[dependencies.finality-tracker]
default_features = false
git = 'https://github.com/paritytech/substrate.git'
package = 'srml-finality-tracker'
rev = 'a2a0eb5398d6223e531455b4c155ef053a4a3a2b'

[dependencies.im-online]
default_features = false
git = 'https://github.com/paritytech/substrate.git'
package = 'srml-im-online'
rev = 'a2a0eb5398d6223e531455b4c155ef053a4a3a2b'

[dependencies.session]
default_features = false
git = 'https://github.com/paritytech/substrate.git'
package = 'srml-session'
rev = 'a2a0eb5398d6223e531455b4c155ef053a4a3a2b'

[dependencies.offences]
default_features = false
git = 'https://github.com/paritytech/substrate.git'
package = 'srml-offences'
rev = 'a2a0eb5398d6223e531455b4c155ef053a4a3a2b'

[dependencies.sr-staking-primitives]
default_features = false
git = 'https://github.com/paritytech/substrate.git'
package = 'sr-staking-primitives'
rev = 'a2a0eb5398d6223e531455b4c155ef053a4a3a2b'

[dependencies.staking]
default_features = false
git = 'https://github.com/paritytech/substrate.git'
package = 'srml-staking'
rev = 'a2a0eb5398d6223e531455b4c155ef053a4a3a2b'

[dependencies.node-primitives]
default_features = false
git = 'https://github.com/paritytech/substrate.git'
package = 'node-primitives'
rev = 'a2a0eb5398d6223e531455b4c155ef053a4a3a2b'

[build-dependencies.wasm-builder-runner]
package = 'substrate-wasm-builder-runner'
version = '1.0.2'

[dependencies.forum]
default_features = false
git = 'https://github.com/mnaamani/substrate-forum-module'
package = 'substrate-forum-module'
branch = 'substrate-v2'
# Before releasing Rome - finalize and tag release new forum and update this
# tag = 'v1.0.0'

[dependencies.versioned-store]
default_features = false
package = 'substrate-versioned-store'
git = 'https://github.com/siman/substrate-versioned-store-module'
branch = 'alex-substrate-v2'